---
- name: Build XGBoost and xgboost4j with dependencies.jar
  hosts: all
  vars:
    xgboost_repo_path: /opt/repos/xgboost
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - build-essential
        - cmake
        - git
        - g++-4.8
        - openjdk-8-jdk
        - maven

    - name: Clone xgboost repository
      git:
        repo: 'https://github.com/dmlc/xgboost.git'
        dest: '{{ xgboost_repo_path }}'
        update: yes
      register: xgboost_repo

    - name: Make
      command: make -j4
      args:
        chdir: '{{ xgboost_repo_path}}'

    - name: Make jvm
      shell: export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 && make jvm
      args:
        chdir: '{{ xgboost_repo_path}}'


    - name: Make jvm-packages
      command: mvn package -Dcheckstyle.skip=true --log-file log.txt
      args:
        chdir: '{{ xgboost_repo_path}}/jvm-packages'


    - name: Copy jvm package to share
      copy:
        src: '{{ xgboost_repo_path }}/jvm-packages/xgboost4j/target/xgboost4j-0.7-jar-with-dependencies.jar'
        dest: '/vagrant/xgboost4j-0.7-SNAPSHOT-{{ xgboost_repo.after }}-jar-with-dependencies.jar'
        remote_src: yes

