---
- name: Configure VM
  hosts: all
  become: true
  tasks:
    - name: Fix locale
      apt:
        name: language-pack-de

        
- name: Setup Jupyter
  hosts: all
  vars:
    anaconda_bin_path: /usr/local/anaconda/bin
  tasks:
    - name: Generate Jupyter config
      command: '{{ anaconda_bin_path }}/jupyter notebook --generate-config'
      args:
        creates: /home/ubuntu/.jupyter/jupyter_notebook_config.py

    - name: Allow external hosts on Jupyter
      lineinfile:
        path: /home/ubuntu/.jupyter/jupyter_notebook_config.py
        regexp: '#c\.NotebookApp\.ip = ''localhost'''
        line: 'c.NotebookApp.ip = ''0.0.0.0'''
        backup: yes
      
    - name: Create folder for Jupyter notebooks
      file:
        path: /vagrant/jupyter
        state: directory

    - name: Clone reveal.js into jupyter/lib to enable speaker notes and offline mode
      git:
        repo: 'https://github.com/hakimel/reveal.js.git'
        dest: /vagrant/jupyter/lib/reveal.js
        update: yes

    - name: Install RISE for Jupyter live presentations
      shell: '{{ anaconda_bin_path }}/conda install -c damianavila82 -y rise'


- name: Install XGBoost
  hosts: all
  become: true
  tasks:
    - name: Install locally built XGBoost python package
      shell: cd /opt/repos/xgboost/python-package &&  /usr/local/anaconda/bin/python setup.py install

    - name: Symlink XGBoost repo to make eg. demo folder accessible in Jupyter
      file:
        src: /opt/repos/xgboost
        dest: /vagrant/jupyter/xgboost
        state: link

        
- name: Install additional packages
  hosts: all
  become: true
  tasks:
    - name: Install LIME (Local Interpretable Model-agnostic Explanations)
      pip:
        name: lime
    - name: Install shap for explaining models with Shapley values
      pip:
        name: shap
